<a href="https://colab.research.google.com/github/2303a51884/2303a51884-pyds-b-02/blob/main/lab_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
matrix1 = np.array([[10, 20, 30],
                       [40, 50, 60],
                       [70, 80, 90]])

matrix2 = np.array([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])

print("Matrix 1:")
print(matrix1)
print("Matrix 2:")
print(matrix2)

matrix_sum = np.add(matrix1, matrix2)
print("Matrix Addition Result:")
print(matrix_sum)

matrix_difference = np.subtract(matrix1,matrix2)
print("Matrix Subtraction Result:")
print(matrix_difference)

Matrix 1:
[[10 20 30]
 [40 50 60]
 [70 80 90]]
Matrix 2:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix Addition Result:
[[11 22 33]
 [44 55 66]
 [77 88 99]]
Matrix Subtraction Result:
[[ 9 18 27]
 [36 45 54]
 [63 72 81]]


In [6]:
import numpy as np

matrix_a = np.array([[1, 2],
                     [3, 4],
                     [5, 6]])

matrix_b = np.array([[7, 8, 9],
                     [10, 11, 12]])

print("Matrix A (3x2):")
print(matrix_a)
print("Matrix B (2x3):")
print(matrix_b)

if matrix_a.shape[1] == matrix_b.shape[0]:
    print("Matrices are compatible for multiplication.")

    dot_product_result = matrix_a @ matrix_b

    print("Result of A @ B (Dot Product):")
    print(dot_product_result)

    manual_calculation = (matrix_a[0, 0] * matrix_b[0, 0]) + (matrix_a[0, 1] * matrix_b[1, 0])
    print(f"\nManual calculation for the element at (0, 0):")
    print(f"({matrix_a[0, 0]} * {matrix_b[0, 0]}) + ({matrix_a[0, 1]} * {matrix_b[1, 0]}) = {manual_calculation}")
    print(f"The calculated result at (0, 0) is {dot_product_result[0, 0]}.")
else:
    print("Matrices are not compatible for multiplication. The number of columns in the first matrix must match the number of rows in the second.")

Matrix A (3x2):
[[1 2]
 [3 4]
 [5 6]]
Matrix B (2x3):
[[ 7  8  9]
 [10 11 12]]
Matrices are compatible for multiplication.
Result of A @ B (Dot Product):
[[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]]

Manual calculation for the element at (0, 0):
(1 * 7) + (2 * 10) = 27
The calculated result at (0, 0) is 27.
